### ISSUE TITLE
build show artifacts broken

### ISSUE THREAD

**Issue by DALDEI** [SurveyMonkey/teamcity_cli#22]
> $ teamcity build show artifacts  odd-app-352
> Traceback (most recent call last):
>   File "/usr/bin/teamcity", line 9, in <module>
>     load_entry_point('teamcity-cli==0.0.0', 'console_scripts', 'teamcity')()
>   File "/usr/lib/python2.7/site-packages/click-6.6-py2.7.egg/click/core.py", line 716, in __call__
>     return self.main(*args, **kwargs)
>   File "/usr/lib/python2.7/site-packages/click-6.6-py2.7.egg/click/core.py", line 696, in main
>     rv = self.invoke(ctx)
>   File "/usr/lib/python2.7/site-packages/click-6.6-py2.7.egg/click/core.py", line 1060, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "/usr/lib/python2.7/site-packages/click-6.6-py2.7.egg/click/core.py", line 1060, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "/usr/lib/python2.7/site-packages/click-6.6-py2.7.egg/click/core.py", line 1060, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "/usr/lib/python2.7/site-packages/click-6.6-py2.7.egg/click/core.py", line 889, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/usr/lib/python2.7/site-packages/click-6.6-py2.7.egg/click/core.py", line 534, in invoke
>     return callback(*args, **kwargs)
>   File "/usr/lib/python2.7/site-packages/click-6.6-py2.7.egg/click/decorators.py", line 17, in new_func
>     return f(get_current_context(), *args, **kwargs)
>   File "/usr/lib/python2.7/site-packages/teamcity_cli-0.0.0-py2.7.egg/teamcitycli.py", line 447, in build_show_artifacts
>     data = ctx.obj.get_build_artifacts_by_build_id(
> AttributeError: TeamCity instance has no attribute 'get_build_artifacts_by_build_id'
>

**Comment by jquast** [comment]
'build list' is broken in the same way,

`AttributeError: 'TeamCity' object has no attribute 'get_all_builds'`

i think it is safe to assume this project abandoned. It would have been nice if the dependencies were pinned in setup.py, here you see the latest version of `pyteamcity` is always used, what version was available when this program worked?

https://github.com/SurveyMonkey/teamcity_cli/blob/master/setup.py#L22

**Comment by aconrad** [comment]
Just curious, can you provide the full traceback?
